logging.level:
  "[org.springframework.security]": TRACE

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:authz.pub
          audiences: cashcards-client
          # issuer-uri: http://localhost:9000
